jupyterhub:
  hub:
    config:
      Authenticator:
        admin_users:
          - jnywong
      JupyterHub:
        authenticate_prometheus: false
    services:
      jupyterhub-groups-exporter: {}
    loadRoles:
      jupyterhub-groups-exporter:
        services:
          - jupyterhub-groups-exporter
        scopes:
          - users
          - groups
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/hub/metrics"
    networkPolicy:
      enabled: true
      interNamespaceAccessLabels: accept
      ingress:
        - from:
          - podSelector:
              matchLabels:
                app: jupyterhub
                component: hub
                hub.jupyter.org/network-access-hub: "true"
          ports:
            - port: 8081
              protocol: TCP
  prePuller:
    continuous:
      enabled: false

jupyterhub-groups-exporter:
  enabled: true
  config:
    groupsExporter:
      update_exporter_interval: 10
      allowed_groups:
        - group-0
        - group-1
      default_group: "test"