prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  kube-state-metrics:
    metricLabelsAllowlist:
      - pods=[app,component,hub.jupyter.org/username,app.kubernetes.io/component]
      - nodes=[*]
      - services=[app, component]
    metricAnnotationsAllowList:
      - pods=[hub.jupyter.org/username]      