prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  kube-state-metrics:
    metricLabelsAllowlist:
      - pods=[app,component,hub.jupyter.org/username,app.kubernetes.io/component]
      - nodes=[*]
      - services=[app, component]
    metricAnnotationsAllowList:
      - pods=[hub.jupyter.org/username]
  networkPolicy:
    enabled: true
  server:
    podLabels:
      hub.jupyter.org/network-access-hub: "true"

grafana:
  adminUser: admin
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        # Automatically add the prometheus server in the same namespace as the grafana as a datasource
        - name: prometheus
          orgId: 1
          type: prometheus
          # This is the name of the kubernetes service exposed by the prometheus server
          url: http://support-prometheus-server
          access: proxy
          isDefault: false
          editable: false
<<<<<<< HEAD
<<<<<<< HEAD:helm/support/support.values.yaml
        - name: jupyterhub-cost-monitoring
=======
        - name: yesoreyeram-infinity-datasource
>>>>>>> 8ebca52 (Add infinity datasource to Grafana)
          type: yesoreyeram-infinity-datasource
          isDefault: false
          editable: true

  plugins:
    - yesoreyeram-infinity-datasource
<<<<<<< HEAD
=======
=======
>>>>>>> 8ebca52 (Add infinity datasource to Grafana)

<<<<<<< HEAD:helm/support/support.values.yaml
cost-monitoring:
  enabled: true
>>>>>>> 485b324 (Local install of cost-monitoring):helm-charts/support/support.values.yaml
=======
jupyterhub-cost-monitoring:
  enabled: true
  extraEnv:
    - name: CLUSTER_NAME
      value: openscapeshub
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-access
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-access
          key: AWS_SECRET_ACCESS_KEY

  image:
    repository: jupyterhub-cost-monitoring
    tag: "latest"
    pullPolicy: Never
>>>>>>> ea5a1e3 (Add instructions for local dev):helm-charts/support/support.values.yaml
